### ISSUE TITLE
Stuck with blind control

### ISSUE THREAD

**Issue by T00bitob** [Sinclair81/Homebridge-Logo-Platform#2]
Hello, I'm new to programming with Logo and after successfully implementing my lights into HomeKit, I went on to try and do the same with my blind. I was wondering if someone could post a template on how they set up their blinds in the Logo! Soft Comfort Software to integrate them with this Homebridge Logo Platform into HomeKit. 

This is probably a stupid question, but I'm still very new to all this. Thank you

**Comment by Sinclair81** [comment]
In the LOGO! Folders are images and UDFs that should help you further.
