### ISSUE TITLE
Adding a new Multi Accessory!

### ISSUE THREAD

**Issue by Sinclair81** [Sinclair81/Homebridge-Logo-Platform#22]
Adding a basic accessory (HomeKit - Other) with no characteristics but the ability to accommodate several children's accessories.

As an example, my controlled living space ventilation:

Ventilation (Other):
- Automatic (switch)
- Level 1 (switch)
- Level 2 (switch)
- Supply air temperature (temp sensor)
- Exhaust air temperature (temp sensor)
- Air quality (air quality sensor)

**Comment by Tellicious** [comment]
Isn't this the same I did with IrrigationSystem and valves? It should be quite easy to extend that to all other accessories

**Comment by Sinclair81** [comment]
Yes, that's how I came up with it. But you have to assign a subtype to each accessory. As an example, my logger tests are in the logger folder.

**Comment by Sinclair81** [comment]
v1.4.3
