### ISSUE TITLE
Homebridge Config UI X not working to create new platform / multiple accessories within one platform

### ISSUE THREAD

**Issue by Tellicious** [Sinclair81/Homebridge-Logo-Platform#3]
Hi, 
when configuring the plugin through Config UI, the generated JS has the "platform" section after the "devices" one and Homebridge is thus not exposing the configured "devices" to HomeKit. Inverting the two sections gets it to work.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/9076397/164680080-a88a0dc0-5d77-4366-a79f-282c358e3080.png">

Also it is not possible to create multiple accessories within the same platform. There is just the possibility to create multiple platforms
<img width="839" alt="image" src="https://user-images.githubusercontent.com/9076397/164679686-4c8fc303-661e-443d-819b-59bb01275a31.png">

Thanks

**Comment by Sinclair81** [comment]
The plugin cannot be configured with the Config UI. The settings are too complex.
