### ISSUE TITLE
Verbindungsproblem mit vw variablen 

### ISSUE THREAD

**Issue by blatorone** [Sinclair81/Homebridge-Logo-Platform#36]
Nach Update von 1.3.8 auf 1.4.0 oder 1.4.1 keine Verbindungen mehr zu Rollos, diese lassen sich nicht mehr steuern. Habe noch Node 18 da ich letzte mal nach einem Update alles neu erstellen musste.
 betrifft auch nur die vw variablen. Einzelne Bits funktionieren weiterhin

**Comment by Sinclair81** [comment]
Also bei mir funktioniert noch alles!?
Schick mir mal bitte Bilder der config und vom LOGO Programm.

**Comment by blatorone** [comment]
![IMG_2392](https://github.com/Sinclair81/Homebridge-Logo-Platform/assets/129631643/d66958a3-7a5e-462a-96c9-988f7cca8807)

Logo Programm kann ich dir momentan leider nicht schicken 🙈, ich habe meinen Laptop nicht hier. Springe ich allerdings wieder zurück auf node 18 und auf 1.3.8 funktioniert alles ohne Probleme

**Comment by Sinclair81** [comment]
Wenn es wirklich eine 0BA1 ist kannst du auf ModBus wechseln!
interfaceType: "modbus",
Dafür muss in der LOGO natürlich auch der ModBus Master aktiv sein.

Bei mir laufen mehrere 0BA7 über snap7 unter 1.4.1 ohne Probleme!
Ich werde aber mal weiter testen mit meiner 0BA0, 0BA1 und snap7.

**Comment by blatorone** [comment]
Ok so hatte ich es mal aber dies ist schon eine Weile her, habe dir beides noch einmal komplett per Mail zukommen lassen

**Comment by Sinclair81** [comment]
Auf die Einstellungen der Logo bin ich sehr gespannt!
Wie ist der Server TSAP auf 0x2800 gekommen? Das geht bei mir nicht als Server!?
Es wird nur von 0x2000 bis 0x2700 für die 8 Server Verbindungen generiert.
<img width="401" alt="Bildschirmfoto 2023-11-18 um 13 58 23" src="https://github.com/Sinclair81/Homebridge-Logo-Platform/assets/21153794/4a8f7a6d-d7fa-4811-8d22-d88fcae32f32">

**Comment by Sinclair81** [comment]
Hm. Tausch mal in der Config local und remote TSAP.

Ich habe in meine Test 0BA1:
lokaler TSAP: 21.00
dezentraler TSAP: 22.00
und in der config:
"localTSAP": "0x2200",
"remoteTSAP": "0x2100",

Ich hatte sie erst gleich, also nicht verdreht. Dann kam keine Verbindung zustande.
Das war aber schon immer so! Es kann aber sein das in node-snap7 eine Überprüfung war und ein automatischer tausch.

**Comment by blatorone** [comment]
Ok, probiere ich morgen mal. Die tsap wurde auf einer Seite automatisch generiert. Das project von mir was ich dir zukommen lassen habe, ist ein Netzwerk project und beim ziehen der Verbindung an verschiedener Stelle generiert sich der tsap von selbst

**Comment by blatorone** [comment]
Habe ich gerade getestet, habe die Logo der Rolladen Steuerung auf tsap 21.00 gestellt und dezentrale tsap auf 22.00. config local 22.00 und dezentral auf 21.00 nichts, gleiches Spiel tausche ich beide kommt keine Verbindung zu Stande und ich erhalte eine Fehlermeldung das keine Verbindung aufgebaut werden kann. Also die Verbindung ist da allerdings bekomme ich keine Werte mehr rein. Ich habe auch einen online Test gemacht und geschaut ob ich die Werte bekomme aber nichts. Und stelle ich es auf 1.3.8 ohne irgend was zu verändern, dann läuft es 😅. Momentan steht alles wieder auf Modbus.

**Comment by Sinclair81** [comment]
Dein Projekt kann ich leider nicht öffnen, "Unbekannter Fehler".
Dann stell lieber alles auf ModBus um!
Es wird wahrscheinlich an dem Netzwerkprojekt liegen.
Ich habe für all meine LOGOs immer einzelne Programme und nur an manchen stellen sind Netzwerk Ein / Ausgänge die in der anderen LOGO Merker oder Ausgänge sind (dann werden die TSAPs auch automatisch generiert aber in der anderen LOGO muss ich die Client Verbindung manuell einrichten).

Schick mir aber trotzdem bitte noch ein Bild von dem Netzwerkprojekt. Ich würde den Fehler gerne bei mir reproduzieren.
Ich habe aber noch nie mit den Netzwerkprojekten gearbeitet.

**Comment by blatorone** [comment]
Ich schicke dir morgen nach der Arbeit mal das einzelne Projekt

**Comment by AleVer254** [comment]
Hello

I seem to have similar problems (VW variables not 'reachable') after the update to node.js v20.x and Homebridge-Logo-Platform 1.4.x. Before I had a network project with 2 logos: 0BA1 and 0BA8 and it worked fine with snap 7.
After reading the comments here above, I did separate the network project into 2 separate 'normal' projects. 

For 0BA1 logo, I use now modbus. The problem with the VW variables are resolved, but I have a strange problem that I can start a light switch, but I cannot stop it anymore? When the V1.4 is put high, it stays high and V1.5 cannot put on high...
<img width="540" alt="image" src="https://github.com/Sinclair81/Homebridge-Logo-Platform/assets/135093165/aca40088-c4b1-4058-8a3c-6ce4457eef57">
<img width="269" alt="image" src="https://github.com/Sinclair81/Homebridge-Logo-Platform/assets/135093165/161cc037-a971-4f3e-a263-33ea252c44e8">

For the 0BA8 logo, I have no other option than to use the snap 7 communication. There, the VW variables problems persists
<img width="1041" alt="image" src="https://github.com/Sinclair81/Homebridge-Logo-Platform/assets/135093165/1f7006e5-a50f-43f0-b6fe-f308412b131b">
Also I have the same problems with the light switches...

What can I do to resolve these problems?

**Comment by Sinclair81** [comment]
I was able to successfully reproduce the problem and thus destroy my entire hombridge installation!
So if possible, always switch to ModBus!!
Now I have to feed my Homebridge Docker container with my devices again. So that I can then continue testing it.

AleVer254 do you have _"pushButton": 1_ for the LOGO?
That will probably help.

**Comment by Sinclair81** [comment]
Please test the latest version 1.4.2!

**Comment by blatorone** [comment]
Everything works fine now 🙂 great work, thanks for editing.

**Comment by AleVer254** [comment]
Here the same, all is working again! Thank you!
