### ISSUE TITLE
Valve Accessory not working

### ISSUE THREAD

**Issue by Tellicious** [Sinclair81/Homebridge-Logo-Platform#4]
Hi,
I cannot get the Valve accessory to work:

Here is my HomeBridge configuration:
{
            "name": "Test Siemens",
            "interface": "modbus",
            "ip": "192.168.1.16",
            "logoType": "0BA0",
            "updateInterval": 2000,
            "debugMsgLog": 0,
            "platform": "LogoPlatform",
            "devices": [
                {
                    "name": "Q7 Output",
                    "type": "switch",
                    "switchGet": "Q7",
                    "switchSetOn": "M32",
                    "switchSetOff": "M33",
                    "pushButton": 1
                },
                {
                    "name": "Q8 Output",
                    "type": "switch",
                    "switchGet": "Q8",
                    "switchSetOn": "M37",
                    "switchSetOff": "M38",
                    "pushButton": 1
                },
                {
                    "name": "Q7 Valve",
                    "type": "valve",
                    "valveGetActive": "V50.2",
                    "valveSetActiveOn": "V50.0",
                    "valveSetActiveOff": "V50.1",
                    "valveGetInUse": "V50.3",
                    "valveType": 1,
                    "valveSetDuration": "VW60",
                    "valveGetDuration": "VW60",
                    "valveGetRemainingDuration": "VW61",
                    "pushButton": 1
                },
                {
                    "name": "Q8 Valve",
                    "type": "valve",
                    "valveGetActive": "V51.2",
                    "valveSetActiveOn": "V51.0",
                    "valveSetActiveOff": "V51.1",
                    "valveGetInUse": "V51.3",
                    "valveType": 1,
                    "valveSetDuration": "VW62",
                    "valveGetDuration": "VW62",
                    "valveGetRemainingDuration": "VW63"
                }
            ]
        }

and here's the Logo program while working
<img width="804" alt="image" src="https://user-images.githubusercontent.com/9076397/164684739-3f1ee495-f385-436f-b148-83edd5922877.png">
<img width="804" alt="image" src="https://user-images.githubusercontent.com/9076397/164684631-a3ec661f-cd08-4ef7-abc1-e16a89e2940f.png">

Issues:
1. When using PushButtons, the valve gets "Active" but it doesn't get "In Use", regardless of whether the Duration is set or not
2. When not using PushButtons, the two inputs remain set and nothing happens
3. The duration in minutes set in Home App gets translated to a different number of seconds (e.g. 5 min to 256 sec) and sometimes you need to set it several times before the Logo gets it

Could you pls support?

Thanks

Andrea

**Comment by Tellicious** [comment]
Ok, I got the valve accessory UDF to work by changing the B045 Analog Watchdog block setting 1 as "Threshold 1" and leaving 0 as "Threshold 0". I'm having a hard time understanding why all that bottom section of the UDF is needed, anyway. With this change you can make it work by first by setting the valve ON and, once it's in Idle, by setting the run time. If the run time is already set and you just toggle the button, it gets just to "Idle". Is this the correct behavior for the HomeKit Valve accessory?

I didn't manage to understand what's happening on my previous point nr 3

**Comment by Sinclair81** [comment]
I adjusted the Valve UDF.
"Active" and "In Use" are activated or deactivated together.
If the time is set to "0", the valve cannot be activated.
