### ISSUE TITLE
Incorrest working of scenes

### ISSUE THREAD

**Issue by pyatnitsev** [Sinclair81/Homebridge-Logo-Platform#6]
Case: 

Two switches (and logo in the switch mode), that actually a blubs.
I created a scene with turn off this switches. It works well if both off or on when I run a scene.
But, if one of them is on and another one is off, I got toggle action, and after it: first one is off, second one is off. 

It would be nice to check state of devices, not just toggle. 
Thanks!

**Comment by Sinclair81** [comment]
But I can't do anything about it. This is how the HomeApp behaves.
A scene only means creating a certain state for several devices. For me everything works as I expect it to. I recorded the screen of my test installation for you.

https://user-images.githubusercontent.com/21153794/177002500-c9abd91a-3fd1-43c6-85ed-db34e071cf6c.mov

**Comment by pyatnitsev** [comment]
ok, thank you.
One more question. What value of pushButton setting in your installation?

**Comment by pyatnitsev** [comment]
I tested this behavior. I see correct commands in HomeBridge log. 
accessory-> set Off. 
But it actually don't checks current state, and if pushButton is true, it's just toggle accessory state. Still looks like a bug.
