### ISSUE TITLE
How to find Mn or Vn.n

### ISSUE THREAD

**Issue by lucas-dehandschutter** [Sinclair81/Homebridge-Logo-Platform#7]
Hello,

In the documentation you mentioned the input value as Mn or Vn.n.

I don't see anything like this in the logosoft application.

I only have Inputs (In) which activates outputs Qn.

Where can I find those Mn or Vn.n ?

Thanks!

**Comment by Sinclair81** [comment]
The lowercase n after the uppercase M or V means number. In most cases a number from 1 to 64 unless there is a dot before the n then it can only be a number from 1 to 8.
