### ISSUE TITLE
Memory leak on RaspberryPi

### ISSUE THREAD

**Issue by Tellicious** [Sinclair81/Homebridge-Logo-Platform#8]
Even with a very simple configuration (5 irrigation valves with modbus) the plug-in keeps increasing its memory usage until it saturates the full 4GB memory, blocking the device. After a few hours from installation it already gets to around 500 MB of memory.

Tried uninstalling / reinstalling and running it as a child bridge without success. The only countermeasure I found so far is to periodically restart Homebridge

**Comment by Sinclair81** [comment]
I hope that your bug fix helps. I think it also has something to do with the Raspberry Pi! My Homebridge runs in a Docker container on a small Intel Atom PC without any problems. After the last 12 days, 5GB of RAM out of 8GB was still free. And I have 5 LOGO!s running with 61 accessories and sensors.

**Comment by Tellicious** [comment]
Yep, basically if you had a _queueInterval_ smaller than _updateInterval_ multiplied by the number of parameters to be updated, the Queue increased indefinitely, as only a part of the requests queued was being sent within _updateInterval_. If _updateInterval_ was not set, everything went smoothly.

With my modification I'm no longer having any issue

By the way I'm also working on adding the option (non-breaking) to set valves as sub-accessories of an Irrigation System and will send you another PR in the next 5-10 days

**Comment by Sinclair81** [comment]
> By the way I'm also working on adding the option (non-breaking) to set valves as sub-accessories of an Irrigation System and will send you another PR in the next 5-10 days

How do you plan to realize that?

It is possible to specify other properties in the accessory if required.
As I did with the leak sensor, it originally has no water level propertie.

**Comment by Tellicious** [comment]
Basically I added another property (`valveParentIrrigationSystem`, optional) to the valve accessory configuration that, once set, prevents the accessory from being created during platform creation. When an irrigation system is instead created, it loops through all the devices configured to find valves with a `valveParentIrrigationSystem` parameter equal to its name. If it finds one, it creates a valve accessory stored in a private array and adds the valve service to its own services.

I am testing it since last Saturday and it is working fine.

I'm adding now an option to IrrigationSystem so that _GetActive_ and _GetInUse_ are automatically derived from its own valves status, if set. After that I just need to do some polishing, adding error messages and do some more tests before sending the PR
