### ISSUE TITLE
Blind doesn't open

### ISSUE THREAD

**Issue by T00bitob** [Sinclair81/Homebridge-Logo-Platform#9]
I successfully implemented the Homebridge-Logo-Platform into Hoobs and connected it to my Logo. The UDF is working. I mean, when I tap onto the blind and try to change its position, it works just fine. But if I click onto the blind in the Home App to either fully close and open it, it doesn't work. I also checked to see if the Analogue Network Input was getting a signal from the action (fully opening or closing) in the Home App, it doesn't seem like it. 

Has anyone else run into this problem or knows how to fix it?

**Comment by AleVer254** [comment]
Hello
I seem to have a similar problem with the garage door accessory. The analogue network input that doesn't change value (after some time) for some unknown reason.

When I start the logo program, everything is working fine. The homebridge-logo-platform can set the garagedoorSetTargetState just fine. But after some time, the SetTargetState is blocked on 0 and only a restart of the logo program and the homebridge server can reset the value to 1. After it's again possible to open/close the garage door with the home app, until the problem restarts.

I've added some print screens that shows the problem.

Somebody have experienced this problem?

Thanks in advance for your help.

<img width="1187" alt="Scherm­afbeelding 2023-06-05 om 10 43 43" src="https://github.com/Sinclair81/Homebridge-Logo-Platform/assets/135093165/627982b6-deca-4300-b000-63621dd4f298">
<img width="639" alt="Scherm­afbeelding 2023-06-05 om 10 44 20" src="https://github.com/Sinclair81/Homebridge-Logo-Platform/assets/135093165/3bd3b319-8560-4202-b24b-7969da7cc949">
<img width="639" alt="Scherm­afbeelding 2023-06-05 om 10 44 56" src="https://github.com/Sinclair81/Homebridge-Logo-Platform/assets/135093165/3ece1633-f27a-4ac9-9fef-d8f4618b52d8">

**Comment by Sinclair81** [comment]
If you have any further questions, just send me an email.
